name = "thermo-solver"
version = "0.1.0"
license = "license"
author = "Daniel Nevius"
maintainer = "dmnevius@ncsu.edu"
copyright = "Copyright 2023, Daniel Nevius"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
